name: CI [backend-app] DEV

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - 'main'
 
jobs:
  Scan:
    name: Snyk scan
    if: ${{ github.event.pull_request.merged == false }}
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/snyk.yaml@main
    with:
      CODEBASE : maven    
    secrets: inherit
