name: CI [backend-app] PROD

on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    name: Build code    
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/maven.yaml@main
    with:
      GH_ENVIRONMENT: PROD    
    secrets: inherit
